import Head from 'next/head'
import Image from 'next/image'

import { Flex, Text } from '@chakra-ui/react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        as="header"

        align="center"
        justifyContent="center"
        h="50"
      >
        <Image src="/images/logo.svg" alt="Logo" width={81} height={20} />
      </Flex>

      <Flex
        as="section"
        direction="column"
        bgImage="/images/mobile-hero-bg.jpg"
        padding="28px 26px 28px 16px"
      >
        <Text textStyle="h1">5 Continentes,<br />infinitas possibilidades.</Text>
        <Text textStyle="h2" marginTop="8px">Chegou a hora de tirar do papel a viagem que você sempre sonhou. </Text>
      </Flex>

    </div>
  )
}
